# Offline mode
offline_mode: 0

sdk: /home/stan/clion/software/build/libPixie16App.so

# Maps the crates to the proper pxisys.ini files.
pxisys_map:
  0: /home/stan/clion/software/usr/local/xia/pixie-sdk/share/pxi/pxisys_14slot_wiener_pxie.ini

# The slot_map tells us what module maps to what crate/slot. E.g. Crate 0, Slot 5 contains Module 0.
slot_map:
  0: # Crate 0
    5: 0 # Slot 5 -> Module 0

# Provides us the location of the firmware files that you're going to be using.
firmware:
  sys: /home/stan/firmware/syspixie16_revfgeneral_adc250mhz_r33339.bin
  fippi: /home/stan/firmware/fippixie16_revfgeneral_16b250m_r36563.bin
  trig: FPGATrig

# Provides the location of the DSP files for booting.
dsp:
  ldr: /home/stan/dsp/Pixie16DSP_revfgeneral_16b250m_r35921.ldr
  var: /home/stan/dsp/Pixie16DSP_revfgeneral_16b250m_r35921.var
  par: /home/stan/configuration/test_ena_cfd_trace_esums.set
