PLXBASE = ./

CC = g++
CFLAGS = -c -Wall
INCFLAGS = -I../software/app -I../software/sys
LDFLAGS = -lm -ldl libPixie16App.a libPixie16Sys.a $(PLXBASE)libPlxApi.a

all: Pixie16Boot Pixie16Test_RevF Pixie16Test_RevF_SNLscaler

Pixie16Boot : Pixie16Boot.o
	$(CC) Pixie16Boot.o -o Pixie16Boot $(LDFLAGS)

Pixie16Test_RevF : Pixie16Test_RevF.o
	$(CC) Pixie16Test_RevF.o -o Pixie16Test_RevF $(LDFLAGS)

Pixie16Test_RevF_SNLscaler : Pixie16Test_RevF_SNLscaler.o
	$(CC) Pixie16Test_RevF_SNLscaler.o -o Pixie16Test_RevF_SNLscaler $(LDFLAGS)

Pixie16Boot.o : Pixie16Boot.c
	$(CC) $(CFLAGS) $(INCFLAGS) Pixie16Boot.c

Pixie16Test_RevF.o : Pixie16Test_RevF.c
	$(CC) $(CFLAGS) $(INCFLAGS) Pixie16Test_RevF.c

Pixie16Test_RevF_SNLscaler.o : Pixie16Test_RevF_SNLscaler.c
	$(CC) $(CFLAGS) $(INCFLAGS) Pixie16Test_RevF_SNLscaler.c

clean:
	rm -f Pixie16Boot.o Pixie16Test_RevF.o Pixie16Test_RevF_SNLscaler.o

cleanall:
	rm -f Pixie16Boot.o Pixie16Test_RevF.o Pixie16Test_RevF_SNLscaler.o Pixie16Boot Pixie16Test_RevF Pixie16Test_RevF_SNLscaler

